version: "3.4"
networks:
  net:
    driver: overlay
    attachable: true
  proxylampy:
    external: true
  serverlampy:
    external: true
services:
  www:
    image: koromerzhin/php:8.4.3-apache-symfony
    depends_on:
      - mariadb
      - mercure
      - mailhog
      - redis
    entrypoint: ["/docker-entrypoint.sh"]
    volumes:
      - ${PWD}/apps:/var/www/:rw
      - ${PWD}/conf/php.ini-development://usr/local/etc/php/conf.d/php.ini
      - ${PWD}/conf/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
      - ${PWD}/conf/apache2/apache2.conf:/etc/apache2/apache2.conf:ro
      - ${PWD}/conf/docker-entrypoint.sh:/docker-entrypoint.sh:ro
    environment:
      APP_SECRET: "CHANGEME"
      MAILER_DSN: "smtp://mailtest:1025"
      MESSENGER_TRANSPORT_DSN: "doctrine://default"
      LOCK_DNS: semaphore
      DATABASE_BDD: prestashop_bdd
      DATABASE_USER: prestashop
      DATABASE_PASSWORD: password
      DATABASE_URL: "mysqli://prestashop:password@mariadb:3306/prestashop_bdd"
    networks:
      - net
      - serverlampy
      - proxylampy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.prestashop.rule=Host(`prestashop.traefik.me`)"
        - "traefik.http.routers.prestashop-tls.tls.domains[0].main=prestashop.traefik.me"
        - "traefik.http.routers.prestashop.tls=true"
        - "traefik.http.services.prestashop.loadbalancer.server.port=80"