version: "3.4"

networks:
  net:
    driver: overlay
    attachable: true
services:
  www:
    image: koromerzhin/phpfpm:8.1.6
    command: sh -c "composer install && php-fpm"
    depends_on:
      - mariadb
      - mercure
      - mailhog
      - redis
    volumes:
      - ${PWD}/apps:/var/www/:delegated
      - ${PWD}/conf/php.ini-development:/usr/local/etc/php/php.ini
      - ${PWD}/conf/docker-php-ram-limit.ini:/usr/local/etc/php/conf.d/docker-php-ram-limit.ini
    networks:
      - net
  phpfpm:
    networks:
      - net